[package]
name = "genesis_empire"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
rand = "0.8.5"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.release]
opt-level = "s"
lto = "thin"
strip = "symbols"
