on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libx11-dev libasound2-dev libudev-dev
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target wasm32-unknown-unknown
      - uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: 'latest'
      - name: Package
        run: |
          mkdir -p dist
          wasm-bindgen --out-dir dist/ --target web ./target/wasm32-unknown-unknown/release/genesis_empire.wasm
          cp website/index.html dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
